language: objective-c
branches:
  only:
  - master
notifications:
  email: false
  
before_install: gem install cocoapods

script: xctool ONLY_ACTIVE_ARCH=YES -workspace KIFtest.xcworkspace -scheme KIFtest build test clean -sdk iphonesimulator
